var Firstname="john";
var Lastname="ryghtu"; 
var age=33;
var Address="dfrhgjhjdg";
var dateOfBirth="12-23-1765";
console.log(Firstname);
console.log(Lastname);
console.log(age);
console.log(Address);
console.log(dateOfBirth);